unique_name: Product Dimension
object_type: dimension
label: Product Dimension
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    filter_empty: 'yes'
    levels:
      - unique_name: Product Category
      - unique_name: Product Sub-Category
      - unique_name: Product Line
      - unique_name: Product Name
      - unique_name: Product Code
level_attributes:
  - unique_name: Product Category
    label: Product Category
    contains_unique_names: false
    dataset: dimproductcategory
    is_unique_key: false
    key_columns:
      - productcategorykey
    name_column: englishproductcategoryname
  - unique_name: Product Sub-Category
    label: Product Sub-Category
    contains_unique_names: false
    dataset: dimproductsubcategory
    is_unique_key: false
    key_columns:
      - productsubcategorykey
    name_column: englishproductsubcategoryname
  - unique_name: Product Line
    label: Product Line
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productline
    name_column: productline
  - unique_name: Product Name
    label: Product Name
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productkey
    name_column: englishproductname
  - unique_name: Product Code
    label: Product Code
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productkey
    name_column: productkey
relationships:
  - from:
      dataset: dimproductsubcategory
      join_columns:
        - productcategorykey
    to:
      level: Product Category
    type: snowflake
  - from:
      dataset: dimproduct
      join_columns:
        - productsubcategorykey
    to:
      level: Product Sub-Category
    type: snowflake
type: standard
