unique_name: Country Security
object_type: row_security
label: Country Security
dataset: geography_sec
filter_key_column: country
id_type: user
ids_column: username
scope: fact
secure_totals: false
use_filter_key: false
