unique_name: Product Security
object_type: row_security
label: Product Security
dataset: Security_Listing
filter_key_column: Value
id_type: user
ids_column: User
scope: all
secure_totals: false
use_filter_key: false
